
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
    fields:
      application: "nginx"
      pid: "access"
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/error.log
    fields:
      application: "nginx"
      pid: "error"
  - type: log
    enabled: true
    paths:
      - /var/log/elasticsearch-initer/log.txt
    fields:
      application: "elastic"
      pid: "initer"
  - type: log
    enabled: true
    paths:
      - /var/log/feedbacks/info.log
    fields:
      application: "feedbacks"
      pid: "info"
  - type: log
    enabled: true
    paths:
      - /var/log/feedbacks/error.log
    fields:
      application: "feedbacks"
      pid: "error"


output.logstash:
  enabled: true
  hosts: ["logstash01:${LOGSTASH_PORT}", "logstash02:${LOGSTASH_PORT}"]

setup.kibana:
  host: "http://kibana:${KIBANA_PORT}"
  username: "${ES_USER}"
  password: "${ES_PASSWORD}"