server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "${ES_PROTOCOL}://${KIBANA_USER}:${KIBANA_PASSWORD}@${ES_HOST}:${ES_PORT}" ]
elasticsearch.username: "${KIBANA_USER}"
elasticsearch.password: "${KIBANA_PASSWORD}"